packages:
  - packages/**
  - playground
  - docs

catalogs:
  prod:
    "@heroui/shared-utils": ^2.1.10
    "@heroui/system": ^2.4.20
    "@heroui/theme": ^2.4.11
    "@heroui/use-aria-button": ^2.2.18
    "@types/node": ^24.3.0
    "@vue/tsconfig": ^0.7.0
    "@vueuse/core": ^11.3.0
    unplugin-vue: ^6.0.1
    vue: ^3.5.13
    vite: "^7.1.2"
    "tailwindcss": "^4.1.12"
    "@tailwindcss/vite": "^4.1.12"
    "@vitejs/plugin-vue": "^6.0.1"

patchedDependencies:
  vitepress: patches/vitepress.patch
